### ISSUE TITLE
3 zipcodes are not supported

### ISSUE THREAD

**Issue by ahmed-bhs** [kylekatarnls/vicopo#20]
Ther's 3 zicpodes are not supported by the api:

75000, 13000 and 69000 !!

**Comment by kylekatarnls** [comment]
Sorry, there're not officially supported zip codes:
https://www.data.gouv.fr/fr/datasets/correspondance-code-insee-code-postal/

For example Paris isn't 75000 because it has 20 zipcodes for each arrondissement: from 75001 to 75020.

It's the same for Lyon and Marseille, if you put 75000 on a mail, it's not supposed to be valid and your letter may not arrive to your recipient.

So it would not be safe to actually add them, for example for an e-commerce that rely on the VICOPO API to send shipments.
